config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do                   # adds all of the RESTful routes for User resource
    member do                           # 'member' method: routes respond to URLs containing user id
      get :following, :followers          # /users/1/following  -> following_user_path(1)
    end                                 # 'collection' method: works w/out the user id
  end                                     # /users/tigers
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get' 
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  

  

end

app/views/shared/_delete_link.html.erb
<% if current_user?(object.user) %>
  <%= link_to "delete", object, method: :delete,
                                data: { confirm: "Are you sure?" },
                                title: object.content %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<!-- pluralize([number], [singular string]):  ActionView::Helpers:TextHelper - returns properly pluralized 
     second argument including many irregular plurals.  e.g: 'woman' -> 'women'; 'erratum' -> 'errata' -->

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

<!-- the :collection parameter (@feed_items) causes render to use the given partial (_feed_item) to render each item in the collection.  Using :collection parameter syntax, we must also include the 'partial' parameter in calling render -->

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
    <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %>
    </span>
    <span class="content"><%= feed_item.content %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
    <%= render partial: 'shared/delete_link', locals: {object: feed_item} %>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>  
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

<!-- form variable (f) can access the associated object through f.object => '@micropost' -->

app/views/shared/_stats.html.erb
<% @user ||= current_user %>        
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>


<!-- b/c 'stats' will be included on user show and home pages, first line picks the correct user
     it does nothing when @user is defined (profile page), but sets @user to current_user when undefined (home page) -->

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 52), current_user %>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>